name: casper_dart_sdk
description: A comprehensive Dart SDK for interacting with the Casper Network blockchain, supporting both Legacy (1.x) and Condor (2.0) networks
version: 0.2.0-condor

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  http: ^1.1.0
  json_annotation: ^4.9.0
  pointycastle: ^3.7.3
  collection: ^1.17.2
  tuple: ^2.0.2
  buffer: ^1.2.2
  cryptography: ^2.7.0
  equatable: ^2.0.5
  basic_utils: ^5.7.0
  secp256k1: ^0.3.0
  convert: ^3.1.1
  rpc_exceptions: ^1.0.1
  jsonrpc2: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.9
  lints: ^3.0.0

dependency_overrides:
  # Ensure compatibility
  crypto: ^3.0.3
  http: ^1.1.0
